[host]
vial_enabled = true
unlock_keys = [[0, 7], [1, 7]]

[keyboard]
name = "ID75"
product_name = "Idobao x YMDK ID75"
vendor_id = 0x594D
product_id = 0x0075
manufacturer = "YMDK"
chip = "rp2040"

[matrix]
row_pins = ["PIN_8", "PIN_6", "PIN_19", "PIN_20", "PIN_18"]
col_pins = ["PIN_26", "PIN_27", "PIN_4", "PIN_5", "PIN_1", "PIN_23", "PIN_22", "PIN_21", "PIN_28", "PIN_3", "PIN_7", "PIN_12", "PIN_13", "PIN_14", "PIN_15"]
row2col = true

[layout]
rows = 5
cols = 15
layers = 2
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9) (0,10) (0,11) (0,12) (0,13) (0,14)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9) (1,10) (1,11) (1,12) (1,13) (1,14)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9) (2,10) (2,11) (2,12) (2,13) (2,14)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8) (3,9) (3,10) (3,11) (3,12) (3,13) (3,14)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6) (4,7) (4,8) (4,9) (4,10) (4,11) (4,12) (4,13) (4,14)
"""

[[layer]]
name = "base_layer"
keys = """
Grave   Kc1   Kc2   Kc3  Kc4   Kc5    Kc6          PrintScreen  Equal         Kc6    Kc7   Kc8     Kc9       Kc0        Minus
Tab     Q     W     E    R     T      LeftBracket  ScrollLock   RightBracket  Y      U     I       O         P          LeftBracket
Escape  A     S     D    F     G      Delete       Up           Backspace     H      J     K       L         Semicolon  Quote
LShift  Z     X     C    V     B      Left         Down         Right         N      M     Comma   Dot       Slash      RShift
LCtrl   LGui  Home  End  LAlt  Space  @mo1         CapsLock     @mo1          Enter  RAlt  PageUp  PageDown  RGui       RCtrl
"""

[[layer]]
name = "func_layer"
keys = """
_  F1    F2    F3        F4      F5   _  _  _  F6    F7  F8    F9     F10    F11
_  _     _     _         _       _    _  _  _  _     _   _     _      _      F12
_  _     Home  PageDown  PageUp  End  _  _  _  Left  Up  Down  Right  _      _
_  _     _     _         _       _    _  _  _  _     _   _     _      _      _
_  _     _     _         _       _    _  _  _  _     _   _     _      _      _
"""

[aliases]
mo1 = "MO(1)"
